{% set name = "roboverse-py" %}
# The latest version available on PIP (0.1.17) has excessive dependency version
# pinning, which includes optional dependencies as required ones. Fortunately,
# the latest commit has more relaxed dependency constraints. Therefore, we use
# the latest commit as the source and version it as 0.1.17.99.
{% set version = "0.1.17.99" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # TODO: Change URL to pypi, once new version is available on PIP
  # https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/roboverse_py-{{ version }}.tar.gz
  - url: https://github.com/RoboVerseOrg/RoboVerse/archive/47b3ebfd55e96117ec2ee4000b6a6a8f6018c182.tar.gz
    sha256: d850f5a8fa5cacbe146a3913d0facc47d668cff5f5eefd9c1ada4003efd5a92c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - dm-control
    - fsspec
    - gymnasium
    - huggingface_hub
    - imageio
    - loguru
    - mujoco-python
    - numpy <2
    - py-opencv
    - pybullet
    - python >={{ python_min }}
    - pytorch
    - rich
    - rootutils
    - torchvision
    - tqdm
    - tyro

test:
  imports:
    - metasim
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/RoboVerseOrg/RoboVerse
  summary: Towards a Unified Platform, Dataset and Benchmark for Scalable and Generalizable Robot Learning
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
